// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa8CqU-vEM5Rex0hsh-6CtXAylrF23ZiM',
    appId: '1:1081395953040:web:1656481b55b0e188084715',
    messagingSenderId: '1081395953040',
    projectId: 'noted-ecd9d',
    authDomain: 'noted-ecd9d.firebaseapp.com',
    storageBucket: 'noted-ecd9d.appspot.com',
    measurementId: 'G-9XH03H0X6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRjq3iOgtE2jc0buryAwHpElse8Pp7nLU',
    appId: '1:1081395953040:android:cbee708162feca16084715',
    messagingSenderId: '1081395953040',
    projectId: 'noted-ecd9d',
    storageBucket: 'noted-ecd9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAa6jVyUEnSBnkJJVs4wFangNFa0LMsSg',
    appId: '1:1081395953040:ios:73c41c50f6e803b9084715',
    messagingSenderId: '1081395953040',
    projectId: 'noted-ecd9d',
    storageBucket: 'noted-ecd9d.appspot.com',
    iosClientId: '1081395953040-vjfgup3mq3l860347pku0hn631i6hs84.apps.googleusercontent.com',
    iosBundleId: 'com.example.noted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAa6jVyUEnSBnkJJVs4wFangNFa0LMsSg',
    appId: '1:1081395953040:ios:4c0ad659ad36ed04084715',
    messagingSenderId: '1081395953040',
    projectId: 'noted-ecd9d',
    storageBucket: 'noted-ecd9d.appspot.com',
    iosClientId: '1081395953040-lkbucenliae7f9brmn6275r6mkeg22sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.noted.RunnerTests',
  );
}
